name: Issue Creation Tracker
on:
  pull_request:
    types: [ opened, reopened, closed ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notification new request
        run: |
          curl --location --request POST '${{ secrets.WEB_HOOK_GOOGLE_CHAT_1 }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "Pull Request",
                          "subtitle": "Pull Request: #${{ github.event.pull_request.number }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                  {
                                     "keyValue": {
                                          "topLabel": "Creator",
                                          "content": "${{ github.event.pull_request.user.login }}"
                                      },
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Title",
                                          "content": "${{ github.event.pull_request.title }}"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Assigned Lables",
                                          "content": "- ${{ join(github.event.pull_request.labels.*.name) }}"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Assignees",
                                          "content": "- ${{ join(github.event.pull_request.assignees.*.login) }}"
                                      }
                                   },
                                   {
                                      "buttons": [
                                          {
                                              "textButton": {
                                                  "text": "OPEN REQUEST",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "${{ github.event.pull_request.html_url }}"
                                                      }
                                                  }
                                              }
                                          }
                                      ]
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'
      - name: Merged request
        if: github.event.pull_request.merged == true
        run: |
          curl --location --request POST '${{ secrets.WEB_HOOK_GOOGLE_CHAT_1 }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "Merge Request",
                          "subtitle": "Merge Request: #${{  github.event.number  }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                  {
                                    "keyValue": {
                                          "topLabel": "Message",
                                          "content": "PR #${{ github.event.number }} has been merged"
                                      },
                                  },
                              ]
                          }
                      ]
                  }
              ]
          }'
